name: EPG Daily Merge & Upload

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  epg-merge-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Repository via Git laden
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin main --depth=1
          git checkout main

      - name: Bibliotheken installieren
        run: |
          python3 -m pip install --upgrade pip
          pip install requests lxml

      - name: EPG Download, Merge & Upload
        env:
          EPG_URL_1: ${{ secrets.EPG_URL_1 }}
          EPG_URL_2: ${{ secrets.EPG_URL_2 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 epg_merge.py
