name: EPG Daily Merge & Upload

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  epg-merge-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Libraries installieren
        run: pip install requests lxml dropbox tqdm

      - name: EPG Download, Merge & Upload
        env:
          EPG_URL_1: ${{ secrets.EPG_URL_1 }}
          EPG_URL_2: ${{ secrets.EPG_URL_2 }}
        run: python epg_merge.py
